Settings:
  Prefix: '&7[&4Crazy &bAuctions&7]: ' #Prefix of when you get Crazy Auctions Messages.
  GUIName: '&4Crazy &bAuctions&8' #Name of the Main GUI.
  Players-Current-Items: '&8Jelenlegi Eladni Kívánt Tárgyaid ' #The Name of the Player Current Items GUI.
  Cancelled/Expired-Items: '&8Törölt/Lejárt Tárgyak' #Name of the Cancelled/Expired GUI.
  Buying-Item: '&8Biztos Vagy Benne?' #Name of the Buying GUI.
  Bidding-On-Item: '&8Licitáltál Erre A Tárgyra.' #Name of the Bidding GUI.
  Categories: '&8Kategóriák' #Name of the Category GUI.
  Sell-Time: 2d #The time that each item will sell for.
  Bid-Time: 2m 30s #Time for each item that is biddable.
  Full-Expire-Time: 10d #The full time the item is in the crazy auctions.
  Bid-Winner-Time: 20d #The time the winner of a bid has to claim there prize.
  Minimum-Sell-Price: 10 #Minimum amount you can sell a item for.
  Max-Beginning-Sell-Price: 10000000 #Max amount you can sell a item for.
  Minimum-Bid-Price: 100 #Minimum starting bid.
  Max-Beginning-Bid-Price: 10000000 #Maximum starting bid.
  Allow-Damaged-Items: True #Allow items that have been damaged.
  Category-Page-Opens-First: False #If set to true the categories page will open when they do /CA.
  Feature-Toggle: #Toggle if a feature is on or off.
    Selling: true #Able to use the selling part of the auction house.
    Bidding: true #Able to use the bidding part of the auction house.
  Sounds:
    Toggle: False #Disable the clicking sound.
    Sound: 'CLICK' #Make sure if you use 1.8 or lower you use the 1.8 sound and 1.9 and up use 1.9 sounds. The default sound is 1.8.
    #1.8 sounds are found here: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
    #1.9 sounds are found here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
  GUISettings: #Settings for things in the gui.
    SellingItemLore: #The lore on items that are being sold.
      - '&7-------------------------'
      - '&aKattints a megvásárlásához.'
      - ''
      - '&9Ár: &e%Price%$'
      - '&9Eladó: &e%Seller%'
      - '&7-------------------------'
    CurrentLore: #Lore on items that are in your current items GUI.
      - '&7-------------------------'
      - '&aKattints a törléshez.'
      - ''
      - '&9Ár: &e%Price%$'
      - '&9Lejár: &e%Time%'
      - '&7-------------------------'
    Cancelled/ExpiredLore: #Lore on items that are in your cancelled/expired GUI.
      - '&7-------------------------'
      - '&aKattints, hogy visszatérjen hozzád.'
      - ''
      - '&9Idő a Teljes Lejáratig: &e%Time%'
      - '&7-------------------------'
    Bidding: #Lore on Bidding Items.
      - '&7-------------------------'
      - '&aKattints a licitáláshoz.'
      - ''
      - '&9Eladó &e%Seller%'
      - '&9Jelenlegi Licit: &e%TopBid%$'
      - '&9Legtöbbet Licitáló: &e%TopBidder%'
      - '&9Hátramaradt Idő: &e%Time%'
      - '&7-------------------------'
    Category-Settings:
      Armor:
        Item: 'GOLDEN_CHESTPLATE'
        Toggle: true
        Slot: 11
        Name: '&6&lPáncélzat'
        Lore:
          - '&7Ez a kategória az összes'
          - '&7eladásra kínált páncélzatot tartalmazza.'
      Weapons:
        Item: 'GOLDEN_SWORD'
        Toggle: true
        Slot: 12
        Name: '&6&lFegyverek'
        Lore:
          - '&7Ez a kategória az összes'
          - '&7eladásra kínált fegyvert tartalmazza.'
      Tools:
        Item: 'GOLDEN_PICKAXE'
        Toggle: true
        Slot: 13
        Name: '&6&lEszközök'
        Lore:
          - '&7Ez a kategória az összes'
          - '&7eladásra kínált eszközt tartalmazza.'
      Food:
        Item: 'GOLDEN_APPLE'
        Toggle: true
        Slot: 14
        Name: '&6&lÉtel'
        Lore:
          - '&7Ez a kategória az összes'
          - '&7eladásra kínált ételt tartalmazza.'
      Potions:
        Item: 'POTION'
        Toggle: true
        Slot: 15
        Name: '&6&lVarázsitalok'
        Lore:
          - '&7Ez a kategória az összes'
          - '&7eladásra kínált varázsitalt tartalmazza.'
      Blocks:
        Item: 'GRASS_BLOCK'
        Toggle: true
        Slot: 16
        Name: '&6&lBlokkok'
        Lore:
          - '&7Ez a kategória az összes'
          - '&7eladásra kínált blokkot tartalmazza.'
      Other:
        Item: 'GOLD_NUGGET'
        Toggle: true
        Slot: 17
        Name: '&6&lEgyéb'
        Lore:
          - '&7Ez a kategória az összes'
          - '&7eladásra kínált egyéb tárgyat tartalmazza.'
      None:
        Item: 'BARRIER'
        Toggle: true
        Slot: 23
        Name: '&6&lÖsszes'
        Lore:
          - '&7Ez a kategória az összes'
          - '&7eladásra kínált tárgyat tartalmazza.'
    OtherSettings: #Other Settings for the GUIs.
      SellingItems: #The button for your current items.
        Item: 'DIAMOND' #The item that this button is.
        Toggle: true #If the item is in the gui or not.
        Slot: 46 #The slot it is in. I recommend not changing these. If you do make sure they are still in the bottom row.
        Name: '&6Eladó Tárgyaid' #Name of the item.
        Lore: #Lore of the item.
          - '&aKattints a jelenleg'
          - '&aeladó tárgyaid megtekintéséhez.'
      Cancelled/ExpiredItems: #The button for Cancelled/Expired Items.
        Item: 'POISONOUS_POTATO'
        Toggle: true
        Slot: 47
        Name: '&6Lejárt / Törölt Tárgyak Összegyűjtése'
        Lore:
          - '&aKattints az összes lejárt vagy'
          - '&atörölt tárgyaid összegyűjtéséhez.'
      PreviousPage: #The button for Previous Page.
        Item: 'PAPER'
        Toggle: true
        Slot: 49
        Name: '&6Előző Oldal'
        Lore: {}
      Refesh: #The button for Refresh Page.
        Item: 'SUNFLOWER'
        Toggle: true
        Slot: 50
        Name: '&6Oldal Újratöltése'
        Lore: {}
      NextPage: #The button for Next Page.
        Item: 'PAPER'
        Toggle: true
        Slot: 51
        Name: '&6Következő Oldal'
        Lore: {}
      Category1: #The button for Next Page.
        Item: 'CHEST'
        Toggle: true
        Slot: 52
        Name: '&6Kategóriák'
        Lore:
          - '&bJelenlegi kategória: &6%Category%'
          - '&aCsak egyetlen kategóriában keresel tárgyakat?'
          - '&aKattints ide a kategóriák megtekintéséhez.'
      Category2: #The button for Next Page.
        Item: 'CHEST'
        Toggle: true
        Slot: 48
        Name: '&6Kategóriák'
        Lore:
          - '&bJelenlegi Kategória: &6%Category%'
          - '&aCsak egyetlen kategóriban keresel tárgyakat?'
          - '&aKattints ide a kategóriák megtekintéséhez.'
      Bidding/Selling: #Switch between Bidding and Selling.
        Selling:
          Item: 'SLIME_BALL'
          Toggle: true
          Slot: 53
          Name: '&6Jelenleg az eladó tárgyakat látod.'
          Lore:
            - '&7&l(&6&l!&7&l) &7Kattints ide, hogy'
            - '&7az árverésen lévő tárgyakat lásd.'
        Bidding:
          Item: 'MAGMA_CREAM'
          Toggle: true
          Slot: 53
          Name: '&6Jelenleg az árverésen lévő tárgyakat látod.'
          Lore:
            - '&7&l(&6&l!&7&l) &7Kattints ide, hogy'
            - '&7az eladó tárgyakat lásd.'
      WhatIsThis: #The info on all the Books buttons.
        SellingShop: #The Book in the main shop.
          Item: 'BOOK'
          Toggle: true
          Slot: 54
          Name: '&6Mi Ez Az Oldal?'
          Lore:
            - '&aEz az aukciós ház, ahol'
            - '&aeladhatsz tárgyakat,'
            - '&avagy vehetsz másoktól.'
            - ''
            - '&aAz aukciós ház jó abban is,'
            - '&ahogy pénzt keress tárgyak eladása által'
            - '&aamik másokat érdekelhetnek.'
        BiddingShop: #The Book in the main shop.
          Item: 'BOOK'
          Toggle: true
          Slot: 54
          Name: '&6Mi Ez Az Oldal?'
          Lore:
            - '&aEz az aukciós ház, ahol'
            - '&aárverésre rakhatsz tárgyakat,'
            - '&avagy licitálhatsz másokéra.'
            - ''
            - '&aAz aukciós ház egyben nagyszerű hely ahhoz is,'
            - '&ahogy pénzt nyerj azáltal, hogy olyan tételeket'
            - '&aajánlasz fel, amelyekre mások licitálhatnak.'
        CurrentItems: #The Book in the Current items GUI.
          Item: 'BOOK'
          Toggle: true
          Slot: 54
          Name: '&6Mi Ez Az Oldal?'
          Lore:
            - '&aAzok a tárgyak, amiket jelenleg'
            - '&a eladásra kínálsz az aukciós házban,'
            - '&aitt jelennek meg.'
            - ''
            - '&aItt meg tudod szüntetni tárgyaid eladását,'
            - '&avagy megnézheted a lejárati idejüket.'
        Cancelled/ExpiredItems: #The Book in the Cancelled/Expired Items GUI.
          Item: 'BOOK'
          Toggle: true
          Slot: 54
          Name: '&6Mi ez az oldal?'
          Lore:
            - '&aEzen az oldalon találod az összes'
            - '&atörölt vagy lejárt tárgyadat.'
            - '&aEzeket a tárgyakat magadhoz'
            - '&ainnen vissza tudod hozni.'
            - ''
            - '&aCsak kattints a tárgyra, ha van'
            - '&aelég hely a leltáradban a visszaszerzéséhez.'
        Viewing: #The Book in the Viewing Items GUI.
          Item: 'BOOK'
          Toggle: true
          Slot: 50
          Name: '&6Mi Ez Az Oldal?'
          Lore:
            - '&aEz az oldal az összes árverésre bocsájtott'
            - '&a, vagy eladó tárgyakat mutatja.'
            - '&aItt gyorsan meg tudod nézni, hogy egy'
            - '&abizonyos játékos éppen mit árul.'
        Categories: #The Book in the Viewing Items GUI.
          Item: 'BOOK'
          Toggle: true
          Slot: 54
          Name: '&6Mi Ez Az Oldal?'
          Lore:
            - '&aEz az oldal megmutatja az összes kategóriát,'
            - '&aahonnan tudsz választani. Mikor rákattintasz'
            - '&aegy kategóriára, akkor csak abban a'
            - '&atémában kereshetsz tárgyakat.'
      Back: #The Back Buttons.
        Item: 'PAPER'
        Slot: 46
        Name: '&6Vissza'
      Return: #The Return Buttons.
        Item: 'FLOWER_POT'
        Slot: 50
        Name: '&6Összes Visszagyűjtése'
        Lore:
          - '&aKattints ide, hogy az összes törölt'
          - '&aés lejárt tárgyadat visszakaphasd.'
      Confirm: #The Confirm Buttons.
        Item: 'LIME_STAINED_GLASS_PANE'
        Name: '&aMegerősítés'
      Cancel: #The Cancel Buttons.
        Item: 'RED_STAINED_GLASS_PANE'
        Name: '&cMégsem'
      Your-Item: #The item that shows when you try to buy/bid on your item.
        Item: 'BARRIER'
        Name: '&cNem Tudod a Saját Tárgyaidat Megvásárolni.'
      Cant-Afford: #The item that shows when you cant afford this item.
        Item: 'BARRIER'
        Name: '&cNincs Erre Elég Pénzed.'
      Top-Bidder: #The item for when a player is already the top bidder.
        Item: 'BARRIER'
        Name: '&cJelenleg te vagy a legtöbbet licitáló.'
      Bidding: #The item in the middle when bidding on an item.
        Item: 'BLACK_STAINED_GLASS_PANE'
        Name: '&7Licitálás'
        Lore:
          - '&7<--&aHozzáad &cTöröl&7-->'
          - '&9Árajánlatod: &e%Bid%$'
          - '&9Jelenlegi Legnagyobb Arajánlat: &e%TopBid%$'
      Bid: #The button for when you want to confirm your bid.
        Item: 'LIGHT_BLUE_STAINED_GLASS_PANE'
        Name: '&bLicitálás Most'
        Lore:
          - '&7Kattints ide az azonnali licitáláshoz.'
  BlackList:
    - 'BEDROCK'
    - 'END_PORTAL_FRAME'
